name: Python application & Docker publish

on:
  push:
    branches: [ main ]      # Build/push uniquement sur main
  pull_request:             # Tests sur PR
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 src test

      - name: Run tests
        run: |
          source venv/bin/activate
          PYTHONPATH=src python -m pytest

  docker:
    needs: test     # Ne se lance que si le job 'test' passe !
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # Build/push uniquement sur main
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/log430-pos:${{ secrets.DOCKER_USERNAME }}